---

- block:
    - validate:
        schema:
          type: object
          properties:
            config:
              type: string
            filename:
              type: string
          required:
            - config
            - filename
        instance: "{{ stackdriver }}"
      register: stackdriver_validated

    - set_fact:
        stackdriver_v: "{{ stackdriver_validated.result }}"

    - name: "Configure the Stackdriver monitoring agent: {{ stackdriver_v.filename }}"
      copy:
        content: "{{ stackdriver_v.config }}"
        dest: "/opt/stackdriver/collectd/etc/collectd.d/{{ stackdriver_v.filename }}.conf"
        force: yes
      notify: stackdriver_reload_monitoring_agent
      become: yes
  tags:
    - stackdriver_configure_monitoring_agent
