---

- block:
    - validate:
        schema:
          type: object
          properties:
            data_source_specification:
              type: string
            metric_descriptor_name:
              type: string
            metric_type:
              type: string
              enum:
                - ABSOLUTE
                - COUNTER
                - DERIVE
                - GAUGE
            plugin_config:
              type: string
            plugin_instance:
              type: string
          required:
            - data_source_specification
            - metric_descriptor_name
            - metric_type
            - plugin_config
            - plugin_instance
        instance: "{{ stackdriver }}"
      register: stackdriver_validated

    - set_fact:
        stackdriver_v: "{{ stackdriver_validated.result }}"

    - name: "Configure the Stackdriver monitoring agent: {{ stackdriver_v.plugin_instance }}"
      template:
        dest: "/etc/stackdriver/collectd.d/{{ stackdriver_v.plugin_instance }}.conf"
        src: custom_metric.conf.j2
        force: yes
      notify: stackdriver_reload_monitoring_agent
      become: yes
  tags:
    - stackdriver_configure_monitoring_agent



    - name: "Enable custom metrics"
      template:
        src: custom_metric.conf.j2
        dest: "/etc/stackdriver/collectd.d/custom_metrics.conf"
        force: yes
      notify: stackdriver_reload_monitoring_agent
      become: yes

