---

- block:
    - validate:
        schema:
          type: object
          properties:
            command:
              type: string
              enum:
                - configure_logging_agent
                - configure_monitoring_agent
                - dependency
                - ingest_unattended_upgrades_log
                - install
          required:
            - command
        instance: "{{ stackdriver }}"

    - include_tasks: '{{ stackdriver.command }}.yml'
  tags:
    - stackdriver
