---

- name: stackdriver_reload_logging_agent
  service:
    name: google-fluentd
    state: reloaded
  become: yes

- name: stackdriver_reload_monitoring_agent
service:
  name: stackdriver-agent
  state: reloaded
become: yes

